### ISSUE TITLE
the data set in the link does not work，could you please release the after processing data set？

### ISSUE THREAD

**Issue by uestcLizhipeng** [vinayakumarr/Network-Intrusion-Detection#1]

**Comment by vinayakumarr** [comment]
KDDCup '99': http://kdd.ics.uci.edu/databases/kddcup99/kddcup99.html

NSL-KDD: http://www.unb.ca/cic/datasets/nsl.html

UNSW-NB15: https://www.unsw.adfa.edu.au/australian-centre-for-cyber-security/cybersecurity/ADFA-NB15-Datasets/

**Comment by TZebin** [comment]
Do you have a description of the pre-processing you applied to the nsl-kDD dataset somewhere? For example, encoding of categorical variables, relabelling of the classes to form binary/ multi-class output, scaling/standardization/normalization etc.

**Comment by vinayakumarr** [comment]
This is very simple. you can write your own code. I don't have that code right now.
