### ISSUE TITLE
Dimension problem when training the dataset after preproceesing 

### ISSUE THREAD

**Issue by thamee** [vinayakumarr/Network-Intrusion-Detection#10]
I try to run your code after preprocess

ing the NSL_KDD dataset but it shows dimension problem like
 "Error when checking input: expected simple_rnn_1_input to have shape (None, 41) but got array with shape (1, 93)"
Can you suggest any idea to solve this

**Comment by vinayakumarr** [comment]
Change the dimension shape from 41 to 93 in input layer
