### ISSUE TITLE
could not convert string to float: 'loadmodule'

### ISSUE THREAD

**Issue by prodhan** [vinayakumarr/Network-Intrusion-Detection#2]
In file: Network-Intrusion-Detection/NSL-KDD/dnn/binary/dnn1.py

I have found this error when I try to run through jupyter notebook:

ValueError                                Traceback (most recent call last)
<ipython-input-5-111e6454d299> in <module>()
     30 testT = np.array(T)
     31 
---> 32 trainX.astype(float)
     33 testT.astype(float)
     34 

ValueError: could not convert string to float: 'loadmodule'

**Comment by vinayakumarr** [comment]
Your input data should not contain any categorical variable.

**Comment by prodhan** [comment]
I have tried with KDDTrain+.csv file. May you share the raw Dataset which you have used. 

Thanks

**Comment by sairupesh** [comment]
I have converted categorical variables using label encoder. But, the accuracy is very less(using random forest). Can you share the cleaned or pre-processed dataset.

**Comment by CodeMonkeyActivity** [comment]
The dataset you used in your code is not in the KDDCup '99': http://kdd.ics.uci.edu/databases/kddcup99/kddcup99.html
