### ISSUE TITLE
Pre-processing of dataset

### ISSUE THREAD

**Issue by PlayerForever** [vinayakumarr/Network-Intrusion-Detection#3]
Hi,

how did you deal with the labels? How to pre-process the labels to fit the models?

Regards,
J.H

**Comment by vinayakumarr** [comment]
You can use labelencoder in sciki-learn

**Comment by PlayerForever** [comment]
Could you pls upload an example for the training dataset? In the dataset I got, labels are in the last column but in your code it looks like the labels are in the first column? Do I need to do some pre-processing on the dataset?

**Comment by PlayerForever** [comment]
Hi, how did you deal with the string features? e.g., Services and protocols?
