### ISSUE TITLE
Features with string values

### ISSUE THREAD

**Issue by PlayerForever** [vinayakumarr/Network-Intrusion-Detection#4]
Hi, how did you deal with the string features? e.g., Services and protocols? It would be nice if you can provide some information about the pre-processing of the dataset. :)

**Comment by StevenLOL** [comment]
One approach is to convert them to one hot encoding.

eg the 2nd feature could be:

|'icmp' |1| 0| 0|
|--|--|--|--|
|'tcp'  |0 | 1 | 0|
|'udp'| 0| 0 | 1 |

**Comment by PlayerForever** [comment]
Hi StevenLOL,

I did it with two encode processes, firstly with labelEncoder and then oneHotEncoder and got further with the experiments. Thanks anyway. :)

Cheers,
J.H.
