### ISSUE TITLE
Regarding NSL-KDD csv file

### ISSUE THREAD

**Issue by deepakkuk** [vinayakumarr/Network-Intrusion-Detection#7]
in NSL-KDD dataset kddtrain.csv and kddtest.csv file not given in public dataset how you convert these file and which one you used for this?
traindata = pd.read_csv('kdd/kddtrain.csv', header=None)
testdata = pd.read_csv('kdd/kddtest.csv', header=None)

**Comment by vinayakumarr** [comment]
you can use preprocessing step to convert the data set into numerical format

**Comment by liudong315** [comment]
> 您可以使用预处理步骤将数据集转换为数字格式

how to use preprocessing step to convert the data set into numerical format? Do you hava the detailed step？

**Comment by soayeb95** [comment]
Use OneHotEncoder() or get_dummies()
