### ISSUE TITLE
The code doesnt work for my kdd cup data

### ISSUE THREAD

**Issue by alawii84** [vinayakumarr/Network-Intrusion-Detection#8]
The code doesnt work for my kdd cup data. can you please share the data you are using.
" traindata = pd.read_csv('kdd/kddtrain.csv', header=None)
testdata = pd.read_csv('kdd/kddtest.csv', header=None)"
Is this the format and the file that we download from the site or is it preprocessed???

**Comment by vinayakumarr** [comment]
you have to apply preprocessing to convert kddcup to numerical format

**Comment by alawii84** [comment]
can you help me by sending the dataset you are converting it. thanks a lot.

**Comment by vinayakumarr** [comment]
Just apply unique number for categorical variable
